# Generated by Django 2.1.7 on 2019-12-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('image_url', models.TextField(verbose_name='图片')),
            ],
            options={
                'db_table': 'tb_mobile_flowImage',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
