# Generated by Django 2.1.7 on 2019-12-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_flowimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowimage',
            name='image_url',
            field=models.URLField(verbose_name='图片'),
        ),
    ]
