# Generated by Django 2.1.7 on 2019-10-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_banner_comments_hotnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hotnews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
    ]
